server {
    listen 80;
    listen [::]:80;
    server_name thamjiththaha.com www.thamjiththaha.com;

    root /var/www/thamjiththaha.com;
    index index.html;

    location / {
        if ($http_user_agent ~* "(curl|wget|httpie|python-requests|go-http-client|lynx)") {
            rewrite ^ /terminal/index.txt last;
        }
        try_files $uri $uri/ /index.html;
    }

    location = /terminal/index.txt {
        default_type text/plain;
        charset utf-8;
        if ($http_user_agent !~* "(curl|wget|httpie|python-requests|go-http-client|lynx)") {
            return 302 /;
        }
    }
}
