server {
    listen 80;
    listen [::]:80;
    server_name thamjiththaha.com www.thamjiththaha.com;
    return 301 https://thamjiththaha.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name thamjiththaha.com www.thamjiththaha.com;

    ssl_certificate /etc/letsencrypt/live/thamjiththaha.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/thamjiththaha.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/thamjiththaha.com;
    index index.html;

    location / {
        if ($http_user_agent ~* "(curl|wget|httpie|python-requests|go-http-client|lynx)") {
            rewrite ^ /terminal/ascii.txt last;
        }
        try_files $uri $uri/ /index.html;
    }

    location = /terminal/ascii.txt {
        default_type text/plain;
        charset utf-8;
        if ($http_user_agent !~* "(curl|wget|httpie|python-requests|go-http-client|lynx)") {
            return 302 /;
        }
    }
}
